import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Basic LLM",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className='h-full' lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-full`}>
                <main className="mx-auto max-w-[1440px] pt-[20px] pb-[50px] h-full">
                    {children}
                </main>
            </body>
        </html>
    );
}
